import pyautogui as p

p.hotkey('win','d')
p.sleep(1)
p.rightClick(p.locateCenterOnScreen('img/icon.png',confidence=0.9))
p.press('up');  p.press('up')
p.press('enter')

p.sleep(0.8)
p.click(p.locateCenterOnScreen('img/recording.png',confidence=0.9))
p.sleep(0.1)
p.click(p.locateCenterOnScreen('img/mic.png',confidence=0.9))
p.sleep(0.1)
p.click(p.locateCenterOnScreen('img/prop.png',confidence=0.9))
p.sleep(0.1)
p.click(p.locateCenterOnScreen('img/listen.png',confidence=0.9))
p.sleep(0.1)
p.click(p.locateCenterOnScreen('img/yeslisten.png',confidence=0.9))
p.sleep(0.1)
p.click(p.locateCenterOnScreen('img/apply.png',confidence=0.9))

p.sleep(0.1)
p.press('esc')
p.press('esc')
p.sleep(0.3)

p.click(p.locateCenterOnScreen('img/icon.png',confidence=0.9))
p.sleep(0.1)
p.click(p.locateCenterOnScreen('img/up.png',confidence=0.9))
p.sleep(0.1)
p.press('up')
p.press('up')
p.press('enter')
p.sleep(0.1)
p.press('esc')
